// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"gorm.io/gorm"
	"school.com/packages/controller/api"
	"school.com/packages/controller/repository"
	repository2 "school.com/packages/internal/adapter/db/repository"
)

// Injectors from wire.go:

func WireStudentController(db *gorm.DB) api.StudentController {
	studentRepository := repository2.ProvideStudentRepository(db)
	studentController := api.ProvideStudentController(studentRepository)
	return studentController
}

func WireTeacherController(db *gorm.DB) api.TeacherController {
	teacherRepository := repository.ProvideTeacherRepository(db)
	teacherController := api.ProvideTeacherController(teacherRepository)
	return teacherController
}

func WireClassroomController(db *gorm.DB) api.ClassroomController {
	classroomRepository := repository.ProvideClassroomRepository(db)
	classroomController := api.ProvideClassroomController(classroomRepository)
	return classroomController
}

func WireClassTeacherController(db *gorm.DB) api.ClassTeacherController {
	classTeacherRepository := repository.ProvideClassTeacherRepository(db)
	classTeacherController := api.ProvideClassTeacherController(classTeacherRepository)
	return classTeacherController
}
